# translator-system/config/default.toml

sys_name = "LaTeXTrans"
version = "0.1.0"
target_language = "ch" # only support Chinese (ch) now
paper_list = ["2501.12948"] # List of paper IDs to process, e.g., ["2505.19590", "2505.19591"]
tex_sources_dir = "tex source" # Directory to store LaTeX source files
output_dir = "outputs" # Directory to store output files
category = {}
update_term = ""

[llm_config]
model = "deepseek-chat"
api_key = "sk-dbce8c36715e412a99fde80c9614661e"
base_url = "https://api.deepseek.com/chat/completions"